#!/usr/bin/env python3
"""Independent replay of the EG203 session-gold computational claims (G28-G31).

Erdos-Graham #203 target:
    exists m, gcd(m,6)=1, such that 2^k * 3^l * m + 1 is composite for all k,l >= 0.

For a prime p > 3, n_p := |<2,3> mod p| is the order of the subgroup of (Z/pZ)*
generated by 2 and 3. Since (Z/pZ)* is cyclic, n_p = lcm(ord_p(2), ord_p(3)).
The exponent pairs (k,l) with p | 2^k 3^l m + 1 form (for admissible m) one coset
of the relation lattice R_p in Z^2, of density 1/n_p.

Replayed claims (see CANONICAL_GOLD.md / docs/provenance/SESSION_GOLD_SWEEP_2026-08-31.md):

  G28  The N=5040 census: primes p>3 with n_p | 5040 number 31, raw mass 143/140.
  G29  N=5040 pool impossibility: the p=5 and p=7 fibres are mandatory, their joint
       image has size exactly 24, so union density <= 143/140 - 1/24 = 823/840 < 1.
  G30  Four-fibre core {5,7,11,13}: all 4*6*10*12 = 2880 phase assignments enumerated
       on the 60x60 torus; max union density = 353/720; overlap tax >= 79/720.
  G31  Low-index census: primes p <= 10^6 with n_p <= 1000 number 238, raw mass
       ~1.8304875993372494, all present by p <= 10^5, largest census prime 67033.

Boundary of this replay:
  * G28's "exactly 31" requires the complete factorization of
    G = gcd(2^5040 - 1, 3^5040 - 1). This script factors G by trial division over
    the structurally-possible primes (p with n_p | 5040 found via order checks on
    divisors of 5040 applied to candidate factors) and reports whether the
    cofactor was fully resolved. If the cofactor is not fully resolved, the count
    is reported as a LOWER BOUND and the receipt says so explicitly.
  * Everything else is exact finite arithmetic.

Output: JSON receipt on stdout and (with --out) to a file. Exit 0 iff every
fully-decided claim matches the banked value.

Python stdlib only. No LLM, no network, no external tools.
"""

import argparse
import hashlib
import json
import math
import sys
from fractions import Fraction


# ---------------------------------------------------------------- primes

def sieve(limit):
    """Return list of primes <= limit."""
    bs = bytearray([1]) * (limit + 1)
    bs[0:2] = b"\x00\x00"
    for i in range(2, int(limit ** 0.5) + 1):
        if bs[i]:
            bs[i * i :: i] = bytearray(len(bs[i * i :: i]))
    return [i for i in range(2, limit + 1) if bs[i]]


def is_probable_prime(n):
    """Deterministic Miller-Rabin for n < 3.3e24 (fixed witness set)."""
    if n < 2:
        return False
    for p in (2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37):
        if n % p == 0:
            return n == p
    d = n - 1
    r = 0
    while d % 2 == 0:
        d //= 2
        r += 1
    for a in (2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37):
        x = pow(a, d, n)
        if x == 1 or x == n - 1:
            continue
        for _ in range(r - 1):
            x = x * x % n
            if x == n - 1:
                break
        else:
            return False
    return True


def multiplicative_order(a, p, p_minus_1_factors):
    """Order of a mod p given the prime factorization of p-1 as {q: e}."""
    order = p - 1
    for q in p_minus_1_factors:
        while order % q == 0 and pow(a, order // q, p) == 1:
            order //= q
    return order


def factorize_small(n, primes):
    """Trial-divide n by the given primes; return ({p: e}, cofactor)."""
    fac = {}
    for p in primes:
        if p * p > n:
            break
        while n % p == 0:
            fac[p] = fac.get(p, 0) + 1
            n //= p
    if n > 1 and (fac or n <= primes[-1] ** 2):
        # remaining cofactor is prime if below square of trial bound
        if n <= primes[-1] ** 2 or is_probable_prime(n):
            fac[n] = fac.get(n, 0) + 1
            n = 1
    return fac, n


def divisors_of(n):
    ds = [1]
    fac = {}
    m = n
    d = 2
    while d * d <= m:
        while m % d == 0:
            fac[d] = fac.get(d, 0) + 1
            m //= d
        d += 1
    if m > 1:
        fac[m] = fac.get(m, 0) + 1
    for q, e in fac.items():
        ds = [x * q ** k for x in ds for k in range(e + 1)]
    return sorted(ds)


# ---------------------------------------------------------------- G28 / G29

def replay_g28_g29(receipt):
    """Census of primes p>3 with n_p | 5040, via factoring gcd(2^5040-1, 3^5040-1)."""
    N = 5040
    G = math.gcd(2 ** N - 1, 3 ** N - 1)

    # Every prime factor p of G has ord_p(2) | 5040 and ord_p(3) | 5040.
    # Pull factors: first trial division by small primes, then by primes found
    # inside 2^d - 1 / 3^d - 1 for divisors d of 5040 (their small factors).
    small = sieve(2_000_000)
    found = {}
    cof = G
    for p in small:
        if p <= 3:
            while cof % p == 0:
                cof //= p  # 2,3 cannot divide G anyway; safety
            continue
        while cof % p == 0:
            found[p] = found.get(p, 0) + 1
            cof //= p
        if cof == 1:
            break

    # Attack remaining cofactor with algebraic-divisor gcds: any prime factor of
    # cof divides gcd(cof, 2^d - 1) for d = ord(2) | 5040, so peel via gcds.
    if cof > 1:
        for d in divisors_of(N):
            if cof == 1:
                break
            g2 = math.gcd(cof, 2 ** d - 1)
            while g2 > 1:
                if is_probable_prime(g2):
                    found[g2] = found.get(g2, 0) + 1
                    cof //= g2
                    g2 = math.gcd(cof, 2 ** d - 1)
                else:
                    # split composite gcd by smaller algebraic divisors
                    split = False
                    for d2 in divisors_of(d)[:-1]:
                        h = math.gcd(g2, 2 ** d2 - 1)
                        if 1 < h < g2:
                            g2 = h
                            split = True
                            break
                    if not split:
                        break
        if cof > 1 and is_probable_prime(cof):
            found[cof] = found.get(cof, 0) + 1
            cof = 1

    fully_resolved = cof == 1
    census = sorted(found)
    # Verify each census prime really has n_p | 5040, and compute exact n_p.
    fibres = []
    for p in census:
        m1 = p - 1
        fac, rem = factorize_small(m1, small)
        assert rem == 1, f"could not factor p-1 for p={p}"
        o2 = multiplicative_order(2, p, fac)
        o3 = multiplicative_order(3, p, fac)
        n_p = o2 * o3 // math.gcd(o2, o3)
        assert N % n_p == 0, f"census prime {p} has n_p={n_p} not dividing 5040"
        fibres.append((p, n_p))
    mass = sum(Fraction(1, n_p) for _, n_p in fibres)

    g28 = {
        "claim": "G28: |U_5040| = 31, raw mass = 143/140",
        "gcd_bit_length": G.bit_length(),
        "census_count": len(fibres),
        "census_complete": fully_resolved,
        "unresolved_cofactor_bit_length": (cof.bit_length() if cof > 1 else 0),
        "raw_mass": f"{mass.numerator}/{mass.denominator}",
        "fibres": [{"p": p, "n_p": n} for p, n in fibres],
        "match": fully_resolved and len(fibres) == 31 and mass == Fraction(143, 140),
    }
    receipt["G28"] = g28

    # G29: mandatory fibres and forced overlap.
    n5 = dict(fibres).get(5)
    n7 = dict(fibres).get(7)
    drop5 = mass - Fraction(1, n5)
    drop7 = mass - Fraction(1, n7)
    # joint image size of (k,l) -> (2^k 3^l mod 5, 2^k 3^l mod 7)
    period = 60
    image = {
        (pow(2, k, 5) * pow(3, l, 5) % 5, pow(2, k, 7) * pow(3, l, 7) % 7)
        for k in range(period)
        for l in range(period)
    }
    bound = mass - Fraction(1, len(image))
    g29 = {
        "claim": "G29: N=5040 pool cannot cover; union <= 823/840 < 1",
        "n_5": n5,
        "n_7": n7,
        "mass_minus_fifth_fibre": f"{drop5.numerator}/{drop5.denominator}",
        "mass_minus_seventh_fibre": f"{drop7.numerator}/{drop7.denominator}",
        "both_mandatory": drop5 < 1 and drop7 < 1,
        "joint_image_size": len(image),
        "union_upper_bound": f"{bound.numerator}/{bound.denominator}",
        "match": (
            n5 == 4
            and n7 == 6
            and drop5 < 1
            and drop7 < 1
            and len(image) == 24
            and bound == Fraction(823, 840)
            and bound < 1
        ),
    }
    receipt["G29"] = g29


# ---------------------------------------------------------------- G30

def replay_g30(receipt):
    """Exhaustive 2880-assignment enumeration for the {5,7,11,13} core on 60x60."""
    primes = [5, 7, 11, 13]
    period = 60
    pts = [(k, l) for k in range(period) for l in range(period)]
    fibre_masks = {}  # p -> list of bitmask (one per phase in <2,3> mod p)
    orders = {}
    for p in primes:
        vals = {}
        for i, (k, l) in enumerate(pts):
            v = pow(2, k, p) * pow(3, l, p) % p
            vals.setdefault(v, 0)
            vals[v] |= 1 << i
        # phases = elements of the subgroup <2,3> mod p = keys of vals
        fibre_masks[p] = list(vals.values())
        orders[p] = len(vals)
    assert [orders[p] for p in primes] == [4, 6, 10, 12], orders
    n_assign = 1
    for p in primes:
        n_assign *= orders[p]

    best = 0
    for m5 in fibre_masks[5]:
        for m7 in fibre_masks[7]:
            m57 = m5 | m7
            for m11 in fibre_masks[11]:
                m0 = m57 | m11
                for m13 in fibre_masks[13]:
                    c = (m0 | m13).bit_count()
                    if c > best:
                        best = c
    max_density = Fraction(best, period * period)
    raw = sum(Fraction(1, orders[p]) for p in primes)
    tax = raw - max_density
    receipt["G30"] = {
        "claim": "G30: max over 2880 assignments = 353/720; overlap tax = 79/720",
        "assignments_enumerated": n_assign,
        "torus_points": period * period,
        "max_union_density": f"{max_density.numerator}/{max_density.denominator}",
        "raw_mass": f"{raw.numerator}/{raw.denominator}",
        "overlap_tax": f"{tax.numerator}/{tax.denominator}",
        "match": (
            n_assign == 2880
            and max_density == Fraction(353, 720)
            and tax == Fraction(79, 720)
        ),
    }


# ---------------------------------------------------------------- G31

def replay_g31(receipt, limit=1_000_000, order_cap=1000):
    """Census of primes p <= 10^6 with n_p <= 1000."""
    primes = sieve(limit)
    small = primes  # for factoring p-1
    fibres = []
    for p in primes:
        if p <= 3:
            continue
        m1 = p - 1
        fac, rem = factorize_small(m1, small)
        if rem != 1:
            raise RuntimeError(f"failed to factor p-1 for p={p}")
        o2 = multiplicative_order(2, p, fac)
        if o2 > order_cap:
            continue
        o3 = multiplicative_order(3, p, fac)
        n_p = o2 * o3 // math.gcd(o2, o3)
        if n_p <= order_cap:
            fibres.append((p, n_p))
    mass = sum(Fraction(1, n) for _, n in fibres)
    largest = max(p for p, _ in fibres)
    complete_by_1e5 = all(p <= 100_000 for p, _ in fibres)
    receipt["G31"] = {
        "claim": (
            "G31: 238 fibres with p <= 10^6, n_p <= 1000; mass ~1.8304875993372494; "
            "complete by p <= 10^5; largest 67033"
        ),
        "census_count": len(fibres),
        "raw_mass_float": float(mass),
        "raw_mass_exact": f"{mass.numerator}/{mass.denominator}",
        "largest_prime": largest,
        "complete_by_1e5": complete_by_1e5,
        "match": (
            len(fibres) == 238
            and largest == 67033
            and complete_by_1e5
            and abs(float(mass) - 1.8304875993372494) < 1e-12
        ),
    }


# ---------------------------------------------------------------- main

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", help="write JSON receipt to this path")
    ap.add_argument("--skip-g31", action="store_true", help="skip the slow census")
    args = ap.parse_args()

    receipt = {
        "replay": "EG203 session gold G28-G31",
        "script_sha256": hashlib.sha256(open(__file__, "rb").read()).hexdigest(),
    }
    replay_g28_g29(receipt)
    replay_g30(receipt)
    if not args.skip_g31:
        replay_g31(receipt)

    decided = [k for k in ("G28", "G29", "G30", "G31") if k in receipt]
    ok = all(receipt[k]["match"] for k in decided)
    receipt["verdict"] = "ALL_MATCH" if ok else "MISMATCH"
    out = json.dumps(receipt, indent=2)
    print(out)
    if args.out:
        with open(args.out, "w") as f:
            f.write(out + "\n")
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
